version: '3.8'

services:

  user-service:
    image: andreyp123/e-shop/user-service:0.1
    container_name: user-service
    build:
      context: ./
      dockerfile: UserSvc.Api/Dockerfile
      args:
        VERSION: 0.1.0
    ports:
      - 8000:8000
    environment:
      - UserRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
    depends_on:
      postgres:
        condition: service_healthy

  billing-service:
    image: andreyp123/e-shop/billing-service:0.1
    container_name: billing-service
    build:
      context: ./
      dockerfile: BillingSvc.Api/Dockerfile
      args:
        VERSION: 0.1.0
    ports:
      - 8002:8002
    environment:
      - AccountRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
    depends_on:
      postgres:
        condition: service_healthy

  order-service:
    image: andreyp123/e-shop/order-service:0.1
    container_name: order-service
    build:
      context: ./
      dockerfile: OrderSvc.Api/Dockerfile
      args:
        VERSION: 0.1.0
    ports:
      - 8004:8004
    environment:
      - OrderRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
      - BillingClient__Url=http://host.docker.internal:8002
      - KafkaProducer__BootstrapServers=kafka:9092
    depends_on:
      postgres:
        condition: service_healthy

  notification-service:
    image: andreyp123/e-shop/notification-service:0.1
    container_name: notification-service
    build:
      context: ./
      dockerfile: NotificationSvc.Api/Dockerfile
      args:
        VERSION: 0.1.0
    ports:
      - 8006:8006
    environment:
      - NotificationRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
      - KafkaConsumer__BootstrapServers=host.docker.internal:9092
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ShopDb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./run/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ShopDb -U sa"]
      interval: 10s
      timeout: 5s
      retries: 6
  
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - 22181:2181
    volumes:
      - ./run/zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - 9092:9092
    volumes:
      - ./run/kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
