version: '3.8'

services:

  user-service-migrator:
    image: andreyp123/e-shop/user-service:0.1
    container_name: user-service-migrator
    command: migrate
    environment:
      - UserRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
    depends_on:
      postgres:
        condition: service_healthy

  billing-service-migrator:
    image: andreyp123/e-shop/billing-service:0.1
    container_name: billing-service-migrator
    command: migrate
    environment:
      - AccountRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
    depends_on:
      postgres:
        condition: service_healthy

  order-service-migrator:
    image: andreyp123/e-shop/order-service:0.1
    container_name: order-service-migrator
    command: migrate
    environment:
      - OrderRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
    depends_on:
      postgres:
        condition: service_healthy

  notification-service-migrator:
    image: andreyp123/e-shop/notification-service:0.1
    container_name: notification-service-migrator
    command: migrate
    environment:
      - NotificationRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ShopDb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./run/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ShopDb -U sa"]
      interval: 10s
      timeout: 5s
      retries: 6
