version: '3.8'

services:

  user-svc-migrator:
    image: andreyp123/eshop-user-svc:0.2
    container_name: user-svc-migrator
    command: migrate
    environment:
      - UserRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
    depends_on:
      postgres:
        condition: service_healthy

  billing-svc-migrator:
    image: andreyp123/eshop-billing-svc:0.2
    container_name: billing-svc-migrator
    command: migrate
    environment:
      - AccountRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
    depends_on:
      postgres:
        condition: service_healthy

  order-svc-migrator:
    image: andreyp123/eshop-order-svc:0.2
    container_name: order-svc-migrator
    command: migrate
    environment:
      - OrderRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
    depends_on:
      postgres:
        condition: service_healthy

  notification-svc-migrator:
    image: andreyp123/eshop-notification-svc:0.2
    container_name: notification-svc-migrator
    command: migrate
    environment:
      - NotificationRepository__ConnectionString=server=postgres;port=5432;database=ShopDb;username=sa;password=sa;
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ShopDb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./run/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ShopDb -U sa"]
      interval: 3s
      timeout: 5s
      retries: 10
