version: '3.8'

services:
  user-manager-test:
    image: andreyp123/user-manager-test:1.0
    container_name: user-manager-test
    build:
      context: ./
      dockerfile: UserManager.WebApi/Dockerfile
      args:
        VERSION: 1.0.0
    ports:
      - 8000:8000
    environment:
      - UserRepository__ConnectionString=server=postgres;port=5432;database=UserDb;username=sa;password=sa;
    depends_on:
      - postgres

  postgres:
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: UserDb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    volumes:
      - ./run/postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.1
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./run/pgadmin-data:/var/lib/pgadmin