apiVersion: batch/v1
kind: Job
metadata:
  name: user-manager-test-migration-job
  namespace: otus-arch-hw02
  labels:
    app: user-manager-test-migration
spec:
  template:
    metadata:
      name: user-manager-test-migration
      labels:
        app: user-manager-test-migration
    spec:
      restartPolicy: Never
      containers:
        - image: andreyp123/user-manager-test:0.5
          name: user-manager-test-migration
          env:
            - name: UserRepository__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: user-manager-test-secret
                  key: DB_CONNECTION_STRING
          command:
            - /migration/UserManager.Repository.Migration
  backoffLimit: 0